SEMI[Semiconductors]:
    ANLG[Analog]:
        - OPA[Operational Amplifier]
        - HSA[High Speed Amplifier]
        - COMP[Comparator]
        - CURR[Current Sense Amplifier]
        - INST[Instrumentation Amplifier]
        - ISOL[Isolation Amplifier]
    DIGI[Digital]:
        - MCU[Microcontroller]
        - TCK[Timer/Clock Generation]
        - IF[Interface]
        - MEM[Memory]
        - LOGI[Logic]
        - COMM[Communications]
    SENS[Sensors]:
        - TEMP[Temperature]
        - AMB[Ambient]
        - IMU[Inertial Measurement Unit]
        - MECH[Mechanical]
        - OPT[Optical]
    PMIC[Power Management ICs]:
        - REG[Power Regulator]
        - CTRL[Switch Controller]
        - LDO[Low Dropout Regulator]
        - CONV[Power Converter]
        - SW[Power Switch]
        - BATT[Battery Management]
    DIOD[Diodes]:
        - RECT[Rectifier]
        - ZEN[Zener]
        - TVS[Transient Voltage Suppressor]
        - SCKY[Schottky]
        - LED[LED]
    XSTR[Transistors]:
        - NPN[NPN Transistor]
        - PNP[PNP Transistor]
        - NMOS[N-Channel MOSFET]
        - PMOS[P-Channel MOSFET]
        - JFET[JFET]
        - IGBT[IGBT]
    MISC[Miscellaneous]:
        - MISC[Miscellaneous]

PASS[Passive]:
    RES[Resistors]:
        - THIN[Thin Film]
        - THCK[Thick Film]
        - HPWR[High Power]
        - POT[Potentiometer]
        - CURR[Current Sense Resistor]
        - NET[Network Resistor]
    CAP[Capacitors]:
        - MLCC[MLCC]
        - TANT[Tantalum]
        - POLY[Polymer]
        - ALUM[Aluminum]
        - FILM[Film]
    IND[Inductors]:
        - PWR[Power Inductor]
        - RF[RF Inductor]
        - CHK[Choke]
        - FB[Ferrite Bead]
        - FILT[Filter]
        - TRF[Transformer]
    PROT[Protection]:
        - FUSE[Fuse]
        - PTC[PTC Thermistor]
        - NTC[NTC Thermistor]
        - VAR[Varistor]
    FCTD[Frequency Control & Timing]:
        - XTAL[Crystal]
        - OSC[Oscillator]
        - RESO[Resonator]
    MISC[Miscellaneous]:
        - MISC[Miscellaneous]

MECH[Mechanical]:
    CONN[Connectors]:
        - TERM[Terminal Block]
        - HDR[Header]
        - RECP[Receptacle]
        - HSG[Housing]
        - CNTC[Contact]
        - USB[USB Connector]
        - PGP[Pogo Pin]
        - WIRE[Wire]
        - ANT[Antennas]
    EMEC[Electromechanical]:
        - PUSH[Push Button]
        - SW[Switch]
        - RLY[Relay]
        - MOT[Motor]
        - BUZZ[Buzzer]
    ENC[Enclosures]:
        - BOX[Box]
        - RACK[Rack Mount]
        - CASE[Case]
    THRM[Thermal Management]:
        - SINK[Heat Sink]
        - FAN[Fan]
        - PADS[Thermal Pads]
        - GREA[Thermal Grease]
        - TAPE[Thermal Tape]
        - INSU[Insulator]
        - TUBE[Heat Shrink Tubing]
    FAST[Fasteners]:
        - SCRW[Screw]
        - NUT[Nut]
        - BOLT[Bolt]
        - WASH[Washer]
        - CLIP[Clip]
        - STND[Standoff]
    MISC[Miscellaneous]:
        - MISC[Miscellaneous]

ASSY[Assembly]:
    PCB[Printed Circuit Board]:
        - FR4[FR4 PCB]
        - FLEX[Flexible PCB]
        - ALUM[Aluminum PCB]
    PCBA[Printed Circuit Board Assembly]:
        - 1LAY[1-Layer Assembly]
        - 2LAY[2-Layer Assembly]
    MISC[Miscellaneous]:
        - MISC[Miscellaneous]
